# -*- coding: utf-8 -*-
"""Copy of Copy of Pandas-assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gR1QJUofcli_dzL83CWqGpKR0D_cV4dr
"""

import numpy as np
import pandas as pd
import io
from google.colab import files

uploaded = files.upload()
df = pd.read_csv(io.StringIO(uploaded['matches.csv'].decode('utf-8')))
df

df.head(3)

# Q1. Find the total number of matches played till now in IPL

df.shape[0]

# Q2. Create a new dataframe from df which will have all the alternate rows and columns from df starting from 0

df.iloc[0:636:2,0:18:2]

# Q3. Find the number of matches played in Mumbai in the period of 2013 and 2017

mask1=df['city']=='Mumbai'
mask2=df['date']>'2013-01-01'
mask3=df['date']<'2017-12-31'
df[mask1 & mask2 & mask3].shape[0]

# Q4. Find the number of matches where the margin of victory was greater than 30

mask=df['win_by_runs']>30
df[mask].shape[0]

# Q5. What percent times KKR decides to bat after winning the toss

mask4=df['toss_winner']=='Kolkata Knight Riders'
mask5=df['toss_decision']=='bat'
db=df[mask4 & mask5].shape[0]
dh=df['toss_winner'].value_counts()
db/dh