# -*- coding: utf-8 -*-
"""Copy of Rahul Singh - Pandas-assignement-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141BQsHtkV4jgtp8KqE8OGtcd-kF8Dnyu
"""

import numpy as np
import pandas as pd
import io
from google.colab import files

uploaded = files.upload()
df = pd.read_csv(io.StringIO(uploaded['matches.csv'].decode('utf-8')))
df

# Q1 : Find the name of the player who won max number of man of the matches award in the period of 2010 and 2015 while plating in Mumbai [Easy]

mask1=df['city']=='Mumbai'
mask2=df['date']>'2010-01-01'
mask3=df['date']<'2015-12-31'
mask4=df['player_of_match']
myseries=df[mask1 & mask2 & mask3 & mask4]
myseries['player_of_match'].value_counts().head(1)

# Q2 : Find the team who has won most number of matches with victory margin > 50 [Easy]

mask1=df['win_by_runs']>50
mask2=df['winner']
myseries=df[mask1 & mask2]
myseries['winner'].value_counts().head(1)

# Q3 : Write a function which will take 2 inputs, team 1 and team 2 and their record against each other

# For example if team1->KKR and team2->CSK
# The output should be like KKR 2(matches won by KKR) and CSK 5(matches won by CSK)[Medium]

def get_teams_record(team1,team2):
 mask1=df['team1']==team1
 mask2=df['team2']==team2
 mask3=df['winner']
 myseries=df[mask1 & mask2 & mask3]
 return myseries['winner'].value_counts()

get_teams_record('Kolkata Knight Riders','Mumbai Indians')

# Q4 : Plot a bar graph on win_by_wickets col. [Easy]

import matplotlib.pyplot as plt
df['win_by_wickets'].value_counts().plot(kind='bar')

# Q5 : Write a function which will accept a team name as input and will return it's win percentage after winning the toss[Difficult]

def get_team_name(team1):
  mask1=df['toss_winner']==team1
  mask2=df['winner']==team1
  mask3=df['team1']
  myseries=df[mask1 & mask2 & mask3]
  return myseries['team1'].value_counts().head(1)

get_team_name('Mumbai Indians')